### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by headius** [ruby/timeout#11]
JRuby's timeout is based on JVM ScheduledExecutor logic that efficiently pools threads. We would like to share the gem so we will need to merge our implementation. We will handle the work necessary.

**Comment by hsbt** [comment]
👍

**Comment by headius** [comment]
I'm going to try to do this in pure-Ruby, since this library is small and the calls into the JDK Executor thread pool would be fairly simple to do from Java.

**Comment by headius** [comment]
#14

**Comment by eregon** [comment]
Added in https://github.com/ruby/timeout/pull/15 and released by hsbt.
