### ISSUE TITLE
Is identical error object check necessary here?

### ISSUE THREAD

**Issue by jjb** [ruby/timeout#38]
The test suite passes with this change (just a demo): https://github.com/jjb/timeout/pull/6/files

If that's acceptable, then the code can be cleaned up like so, with the benefits of being more readable and also creating fewer objects per invocation: https://github.com/jjb/timeout/pull/5/files

If it's not acceptable, I could make a PR which adds a test.

**Comment by eregon** [comment]
The check is meant to ensure it's the correct ExitException we raised that we see, not another one, and only translate to Timeout::Error if so.

Notably for cases of nesting Timeout.timeout calls and the outer timeout is smaller than the inner timeout, the inner timeout call should not raise, only the outer one.
The test suite should fail for this change, it means we are missing a test for that case.

**Comment by eregon** [comment]
We have https://github.com/ruby/timeout/blob/03873a9237dd55757ed149603f9dea7af3f56788/test/test_timeout.rb#L53-L64 but it's missing a check to ensure the inner timeout calls does not raise Timeout::Error.

**Comment by jjb** [comment]
Great

here are a couple tests i threw together

the second one does fail with the diff discussed above

not sure how close this is to what you have in mind for what should be tested

any feedback welcome!

https://github.com/ruby/timeout/pull/39/files

**Comment by eregon** [comment]
Tests added in https://github.com/ruby/timeout/pull/39 so I think we can close this.

**Comment by jjb** [comment]
confirmed that with new tests, my PRs in original post above are no longer green

https://github.com/jjb/timeout/pull/5

https://github.com/jjb/timeout/pull/6
