### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by voxik** [ruby/timeout#44]
The [license file](https://github.com/ruby/timeout/blob/master/LICENSE.txt) contains BSD-2-Clause license, while gemspec specifies [Ruby OR BSD-2-Clause](https://github.com/ruby/timeout/blob/d1d2263b3b3d88b818e085ba91341db0ba9b6706/timeout.gemspec#L19). Assuming the latter is correct, how to capture this information? Is COPYING file similar to Ruby the way to go?

**Comment by hsbt** [comment]
Fixed at https://github.com/ruby/timeout/commit/6c99460887e820c54ee7c19350b93bdc58785fca
